/**
 * NovaCargo Mock Data
 * 35 realistic shipments with full tracking histories,
 * sender/receiver info, and timeline events.
 */

// ─── Status options ───────────────────────────────────────────────────────────
export const STATUS = {
  PENDING: "Pending",
  PROCESSING: "Processing",
  IN_TRANSIT: "In Transit",
  OUT_FOR_DELIVERY: "Out for Delivery",
  DELIVERED: "Delivered",
  DELAYED: "Delayed",
  RETURNED: "Returned",
};

// ─── Color map for status badges ─────────────────────────────────────────────
export const STATUS_COLORS = {
  [STATUS.PENDING]: {
    bg: "bg-slate-100",
    text: "text-slate-700",
    dot: "bg-slate-400",
  },
  [STATUS.PROCESSING]: {
    bg: "bg-blue-100",
    text: "text-blue-700",
    dot: "bg-blue-500",
  },
  [STATUS.IN_TRANSIT]: {
    bg: "bg-amber-100",
    text: "text-amber-700",
    dot: "bg-amber-500",
  },
  [STATUS.OUT_FOR_DELIVERY]: {
    bg: "bg-orange-100",
    text: "text-orange-700",
    dot: "bg-orange-500",
  },
  [STATUS.DELIVERED]: {
    bg: "bg-green-100",
    text: "text-green-700",
    dot: "bg-green-500",
  },
  [STATUS.DELAYED]: {
    bg: "bg-red-100",
    text: "text-red-700",
    dot: "bg-red-500",
  },
  [STATUS.RETURNED]: {
    bg: "bg-purple-100",
    text: "text-purple-700",
    dot: "bg-purple-500",
  },
};

// ─── Service types ────────────────────────────────────────────────────────────
export const SERVICE_TYPES = [
  "Express Delivery",
  "Standard Shipping",
  "International Air",
  "Freight Services",
  "Same-Day Delivery",
  "Economy Shipping",
];

// ─── Helper to generate realistic dates ──────────────────────────────────────
function daysAgo(n) {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

function daysFromNow(n) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().split("T")[0];
}

function formatDate(isoStr) {
  return new Date(isoStr).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function formatDateTime(isoStr, timeStr) {
  return `${formatDate(isoStr)} ${timeStr}`;
}

// ─── Tracking timeline builder ────────────────────────────────────────────────
function buildTimeline(status, origin, destination, startDateOffset) {
  const base = daysAgo(startDateOffset);
  const events = [];

  events.push({
    id: 1,
    status: "Order Received",
    description: `Shipment booked at ${origin} facility`,
    location: origin,
    date: formatDateTime(base, "09:14 AM"),
    completed: true,
  });

  if (
    [
      STATUS.PROCESSING,
      STATUS.IN_TRANSIT,
      STATUS.OUT_FOR_DELIVERY,
      STATUS.DELIVERED,
      STATUS.DELAYED,
    ].includes(status)
  ) {
    events.push({
      id: 2,
      status: "Package Picked Up",
      description: "Package collected from sender and processed at sorting hub",
      location: origin,
      date: formatDateTime(daysAgo(startDateOffset - 1), "02:30 PM"),
      completed: true,
    });
  }

  if (
    [
      STATUS.IN_TRANSIT,
      STATUS.OUT_FOR_DELIVERY,
      STATUS.DELIVERED,
      STATUS.DELAYED,
    ].includes(status)
  ) {
    events.push({
      id: 3,
      status: "In Transit",
      description: "Package en route to destination — cleared customs",
      location: "International Hub",
      date: formatDateTime(daysAgo(startDateOffset - 2), "11:05 AM"),
      completed: true,
    });
    events.push({
      id: 4,
      status: "Arrived at Hub",
      description: `Package arrived at ${destination} distribution center`,
      location: destination,
      date: formatDateTime(daysAgo(startDateOffset - 3), "07:45 AM"),
      completed: true,
    });
  }

  if ([STATUS.OUT_FOR_DELIVERY, STATUS.DELIVERED].includes(status)) {
    events.push({
      id: 5,
      status: "Out for Delivery",
      description: "Package loaded onto delivery vehicle",
      location: destination,
      date: formatDateTime(daysAgo(1), "08:20 AM"),
      completed: true,
    });
  }

  if (status === STATUS.DELIVERED) {
    events.push({
      id: 6,
      status: "Delivered",
      description: "Package successfully delivered to recipient",
      location: destination,
      date: formatDateTime(daysAgo(0), "01:37 PM"),
      completed: true,
    });
  }

  if (status === STATUS.DELAYED) {
    events.push({
      id: 5,
      status: "Delivery Delayed",
      description: "Delay due to severe weather conditions — rescheduled",
      location: "Regional Depot",
      date: formatDateTime(daysAgo(1), "03:00 PM"),
      completed: false,
      isAlert: true,
    });
  }

  if (status === STATUS.RETURNED) {
    events.push({
      id: 5,
      status: "Return Initiated",
      description: "Delivery failed — package returned to sender",
      location: destination,
      date: formatDateTime(daysAgo(1), "10:15 AM"),
      completed: false,
      isAlert: true,
    });
  }

  return events;
}

// ─── 35 Shipment Records ─────────────────────────────────────────────────────
export const shipments = [
  {
    id: "NC-2024-001",
    trackingNumber: "NC7841203648",
    status: STATUS.DELIVERED,
    service: "Express Delivery",
    weight: "2.4 kg",
    dimensions: "35 × 22 × 14 cm",
    sender: { name: "Apex Electronics Ltd.", city: "Shenzhen", country: "China" },
    receiver: { name: "Marcus Bellamy", city: "London", country: "United Kingdom" },
    origin: "Shenzhen, China",
    destination: "London, UK",
    currentLocation: "London, UK",
    estimatedDelivery: daysAgo(0),
    actualDelivery: daysAgo(0),
    shippedDate: daysAgo(7),
    timeline: buildTimeline(STATUS.DELIVERED, "Shenzhen, China", "London, UK", 7),
    description: "Consumer Electronics",
  },
  {
    id: "NC-2024-002",
    trackingNumber: "NC5293817402",
    status: STATUS.IN_TRANSIT,
    service: "International Air",
    weight: "5.8 kg",
    dimensions: "60 × 40 × 30 cm",
    sender: { name: "GlobalMed Supplies", city: "Frankfurt", country: "Germany" },
    receiver: { name: "City Hospital", city: "Nairobi", country: "Kenya" },
    origin: "Frankfurt, Germany",
    destination: "Nairobi, Kenya",
    currentLocation: "International Hub, Dubai",
    estimatedDelivery: daysFromNow(2),
    shippedDate: daysAgo(3),
    timeline: buildTimeline(STATUS.IN_TRANSIT, "Frankfurt, Germany", "Nairobi, Kenya", 3),
    description: "Medical Equipment",
  },
  {
    id: "NC-2024-003",
    trackingNumber: "NC1047382915",
    status: STATUS.OUT_FOR_DELIVERY,
    service: "Same-Day Delivery",
    weight: "0.8 kg",
    dimensions: "20 × 15 × 10 cm",
    sender: { name: "Bloom Botanics", city: "Amsterdam", country: "Netherlands" },
    receiver: { name: "Sophia Chen", city: "Amsterdam", country: "Netherlands" },
    origin: "Amsterdam, Netherlands",
    destination: "Amsterdam, Netherlands",
    currentLocation: "Delivery Vehicle — Zone 4",
    estimatedDelivery: daysFromNow(0),
    shippedDate: daysAgo(1),
    timeline: buildTimeline(STATUS.OUT_FOR_DELIVERY, "Amsterdam, NL", "Amsterdam, NL", 1),
    description: "Fresh Flowers",
  },
  {
    id: "NC-2024-004",
    trackingNumber: "NC9384720561",
    status: STATUS.PENDING,
    service: "Economy Shipping",
    weight: "12.3 kg",
    dimensions: "80 × 60 × 50 cm",
    sender: { name: "Vertex Furniture Co.", city: "Warsaw", country: "Poland" },
    receiver: { name: "HomeDecor Studio", city: "Madrid", country: "Spain" },
    origin: "Warsaw, Poland",
    destination: "Madrid, Spain",
    currentLocation: "Warsaw, Poland",
    estimatedDelivery: daysFromNow(8),
    shippedDate: daysAgo(0),
    timeline: buildTimeline(STATUS.PENDING, "Warsaw, Poland", "Madrid, Spain", 0),
    description: "Furniture Parts",
  },
  {
    id: "NC-2024-005",
    trackingNumber: "NC3827461092",
    status: STATUS.DELAYED,
    service: "Standard Shipping",
    weight: "3.2 kg",
    dimensions: "40 × 30 × 20 cm",
    sender: { name: "TechVault Inc.", city: "Toronto", country: "Canada" },
    receiver: { name: "Dev Solutions LLC", city: "Chicago", country: "United States" },
    origin: "Toronto, Canada",
    destination: "Chicago, USA",
    currentLocation: "Regional Depot, Buffalo",
    estimatedDelivery: daysFromNow(3),
    shippedDate: daysAgo(5),
    timeline: buildTimeline(STATUS.DELAYED, "Toronto, Canada", "Chicago, USA", 5),
    description: "Server Components",
  },
  {
    id: "NC-2024-006",
    trackingNumber: "NC6174839205",
    status: STATUS.DELIVERED,
    service: "Express Delivery",
    weight: "1.1 kg",
    dimensions: "25 × 18 × 8 cm",
    sender: { name: "LuxeWear Paris", city: "Paris", country: "France" },
    receiver: { name: "Amara Okonkwo", city: "Lagos", country: "Nigeria" },
    origin: "Paris, France",
    destination: "Lagos, Nigeria",
    currentLocation: "Lagos, Nigeria",
    estimatedDelivery: daysAgo(1),
    actualDelivery: daysAgo(1),
    shippedDate: daysAgo(6),
    timeline: buildTimeline(STATUS.DELIVERED, "Paris, France", "Lagos, Nigeria", 6),
    description: "Luxury Apparel",
  },
  {
    id: "NC-2024-007",
    trackingNumber: "NC8203947165",
    status: STATUS.PROCESSING,
    service: "Freight Services",
    weight: "48.7 kg",
    dimensions: "120 × 80 × 70 cm",
    sender: { name: "AutoParts Express", city: "Detroit", country: "United States" },
    receiver: { name: "Motors Plus GmbH", city: "Stuttgart", country: "Germany" },
    origin: "Detroit, USA",
    destination: "Stuttgart, Germany",
    currentLocation: "Detroit Freight Terminal",
    estimatedDelivery: daysFromNow(10),
    shippedDate: daysAgo(1),
    timeline: buildTimeline(STATUS.PROCESSING, "Detroit, USA", "Stuttgart, Germany", 1),
    description: "Automotive Parts",
  },
  {
    id: "NC-2024-008",
    trackingNumber: "NC4729381056",
    status: STATUS.IN_TRANSIT,
    service: "International Air",
    weight: "2.9 kg",
    dimensions: "30 × 25 × 15 cm",
    sender: { name: "SakuraTech", city: "Tokyo", country: "Japan" },
    receiver: { name: "Nexus Retail", city: "Sydney", country: "Australia" },
    origin: "Tokyo, Japan",
    destination: "Sydney, Australia",
    currentLocation: "Singapore International Hub",
    estimatedDelivery: daysFromNow(1),
    shippedDate: daysAgo(4),
    timeline: buildTimeline(STATUS.IN_TRANSIT, "Tokyo, Japan", "Sydney, Australia", 4),
    description: "Smart Devices",
  },
  {
    id: "NC-2024-009",
    trackingNumber: "NC0583726491",
    status: STATUS.DELIVERED,
    service: "Standard Shipping",
    weight: "4.6 kg",
    dimensions: "45 × 35 × 25 cm",
    sender: { name: "BookWorld Publishing", city: "New York", country: "United States" },
    receiver: { name: "Cairo University", city: "Cairo", country: "Egypt" },
    origin: "New York, USA",
    destination: "Cairo, Egypt",
    currentLocation: "Cairo, Egypt",
    estimatedDelivery: daysAgo(2),
    actualDelivery: daysAgo(2),
    shippedDate: daysAgo(9),
    timeline: buildTimeline(STATUS.DELIVERED, "New York, USA", "Cairo, Egypt", 9),
    description: "Academic Books",
  },
  {
    id: "NC-2024-010",
    trackingNumber: "NC7362819405",
    status: STATUS.OUT_FOR_DELIVERY,
    service: "Express Delivery",
    weight: "1.7 kg",
    dimensions: "28 × 20 × 12 cm",
    sender: { name: "Alpine Sports AG", city: "Zurich", country: "Switzerland" },
    receiver: { name: "James Whitfield", city: "Vienna", country: "Austria" },
    origin: "Zurich, Switzerland",
    destination: "Vienna, Austria",
    currentLocation: "Vienna Delivery Hub",
    estimatedDelivery: daysFromNow(0),
    shippedDate: daysAgo(2),
    timeline: buildTimeline(STATUS.OUT_FOR_DELIVERY, "Zurich, Switzerland", "Vienna, Austria", 2),
    description: "Sports Equipment",
  },
  {
    id: "NC-2024-011",
    trackingNumber: "NC2918374056",
    status: STATUS.IN_TRANSIT,
    service: "Freight Services",
    weight: "230 kg",
    dimensions: "200 × 150 × 120 cm",
    sender: { name: "Harvest Foods Co.", city: "São Paulo", country: "Brazil" },
    receiver: { name: "SuperMart Europe", city: "Lisbon", country: "Portugal" },
    origin: "São Paulo, Brazil",
    destination: "Lisbon, Portugal",
    currentLocation: "Mid-Atlantic Shipping Lane",
    estimatedDelivery: daysFromNow(5),
    shippedDate: daysAgo(8),
    timeline: buildTimeline(STATUS.IN_TRANSIT, "São Paulo, Brazil", "Lisbon, Portugal", 8),
    description: "Food & Beverages",
  },
  {
    id: "NC-2024-012",
    trackingNumber: "NC5841729036",
    status: STATUS.RETURNED,
    service: "Economy Shipping",
    weight: "0.6 kg",
    dimensions: "18 × 12 × 8 cm",
    sender: { name: "Online Boutique", city: "Milan", country: "Italy" },
    receiver: { name: "Incorrect Address", city: "Brussels", country: "Belgium" },
    origin: "Milan, Italy",
    destination: "Brussels, Belgium",
    currentLocation: "Milan, Italy",
    estimatedDelivery: daysAgo(3),
    shippedDate: daysAgo(7),
    timeline: buildTimeline(STATUS.RETURNED, "Milan, Italy", "Brussels, Belgium", 7),
    description: "Fashion Accessories",
  },
  {
    id: "NC-2024-013",
    trackingNumber: "NC3049182756",
    status: STATUS.DELIVERED,
    service: "Same-Day Delivery",
    weight: "3.5 kg",
    dimensions: "40 × 30 × 20 cm",
    sender: { name: "FreshMart Grocery", city: "Dubai", country: "UAE" },
    receiver: { name: "Khalid Al Rashidi", city: "Dubai", country: "UAE" },
    origin: "Dubai, UAE",
    destination: "Dubai, UAE",
    currentLocation: "Dubai, UAE",
    estimatedDelivery: daysAgo(0),
    actualDelivery: daysAgo(0),
    shippedDate: daysAgo(0),
    timeline: buildTimeline(STATUS.DELIVERED, "Dubai, UAE", "Dubai, UAE", 0),
    description: "Groceries",
  },
  {
    id: "NC-2024-014",
    trackingNumber: "NC8172039465",
    status: STATUS.IN_TRANSIT,
    service: "International Air",
    weight: "7.2 kg",
    dimensions: "55 × 42 × 28 cm",
    sender: { name: "Pharma Dynamics", city: "Mumbai", country: "India" },
    receiver: { name: "HealthPlus Chain", city: "Jakarta", country: "Indonesia" },
    origin: "Mumbai, India",
    destination: "Jakarta, Indonesia",
    currentLocation: "Kuala Lumpur Hub",
    estimatedDelivery: daysFromNow(2),
    shippedDate: daysAgo(3),
    timeline: buildTimeline(STATUS.IN_TRANSIT, "Mumbai, India", "Jakarta, Indonesia", 3),
    description: "Pharmaceutical Products",
  },
  {
    id: "NC-2024-015",
    trackingNumber: "NC6394817502",
    status: STATUS.PROCESSING,
    service: "Express Delivery",
    weight: "1.4 kg",
    dimensions: "22 × 18 × 10 cm",
    sender: { name: "NovaCargo HQ", city: "Amsterdam", country: "Netherlands" },
    receiver: { name: "Elena Vasquez", city: "Buenos Aires", country: "Argentina" },
    origin: "Amsterdam, Netherlands",
    destination: "Buenos Aires, Argentina",
    currentLocation: "Amsterdam, Netherlands",
    estimatedDelivery: daysFromNow(4),
    shippedDate: daysAgo(1),
    timeline: buildTimeline(STATUS.PROCESSING, "Amsterdam, NL", "Buenos Aires, Argentina", 1),
    description: "Documents & Contracts",
  },
  {
    id: "NC-2024-016",
    trackingNumber: "NC7581930246",
    status: STATUS.DELIVERED,
    service: "Standard Shipping",
    weight: "9.1 kg",
    dimensions: "70 × 50 × 40 cm",
    sender: { name: "CraftWood Studios", city: "Helsinki", country: "Finland" },
    receiver: { name: "Interior Hub", city: "Stockholm", country: "Sweden" },
    origin: "Helsinki, Finland",
    destination: "Stockholm, Sweden",
    currentLocation: "Stockholm, Sweden",
    estimatedDelivery: daysAgo(1),
    actualDelivery: daysAgo(1),
    shippedDate: daysAgo(5),
    timeline: buildTimeline(STATUS.DELIVERED, "Helsinki, Finland", "Stockholm, Sweden", 5),
    description: "Handcrafted Goods",
  },
  {
    id: "NC-2024-017",
    trackingNumber: "NC2047391856",
    status: STATUS.DELAYED,
    service: "International Air",
    weight: "3.8 kg",
    dimensions: "38 × 28 × 18 cm",
    sender: { name: "KoreanBeauty Co.", city: "Seoul", country: "South Korea" },
    receiver: { name: "Beauty Box UK", city: "Manchester", country: "United Kingdom" },
    origin: "Seoul, South Korea",
    destination: "Manchester, UK",
    currentLocation: "Customs Hold, Heathrow",
    estimatedDelivery: daysFromNow(2),
    shippedDate: daysAgo(6),
    timeline: buildTimeline(STATUS.DELAYED, "Seoul, South Korea", "Manchester, UK", 6),
    description: "Cosmetics & Skincare",
  },
  {
    id: "NC-2024-018",
    trackingNumber: "NC9283741650",
    status: STATUS.OUT_FOR_DELIVERY,
    service: "Express Delivery",
    weight: "0.5 kg",
    dimensions: "15 × 12 × 6 cm",
    sender: { name: "Artisan Jewels", city: "Florence", country: "Italy" },
    receiver: { name: "Priya Nair", city: "Rome", country: "Italy" },
    origin: "Florence, Italy",
    destination: "Rome, Italy",
    currentLocation: "Rome South Depot",
    estimatedDelivery: daysFromNow(0),
    shippedDate: daysAgo(1),
    timeline: buildTimeline(STATUS.OUT_FOR_DELIVERY, "Florence, Italy", "Rome, Italy", 1),
    description: "Fine Jewelry",
  },
  {
    id: "NC-2024-019",
    trackingNumber: "NC4816273059",
    status: STATUS.IN_TRANSIT,
    service: "Freight Services",
    weight: "180 kg",
    dimensions: "180 × 130 × 100 cm",
    sender: { name: "Pacific Machinery", city: "Guangzhou", country: "China" },
    receiver: { name: "BuildCo Ltd.", city: "Johannesburg", country: "South Africa" },
    origin: "Guangzhou, China",
    destination: "Johannesburg, South Africa",
    currentLocation: "Port of Durban",
    estimatedDelivery: daysFromNow(3),
    shippedDate: daysAgo(14),
    timeline: buildTimeline(STATUS.IN_TRANSIT, "Guangzhou, China", "Johannesburg, SA", 14),
    description: "Industrial Machinery",
  },
  {
    id: "NC-2024-020",
    trackingNumber: "NC1534892076",
    status: STATUS.DELIVERED,
    service: "Same-Day Delivery",
    weight: "2.1 kg",
    dimensions: "30 × 22 × 15 cm",
    sender: { name: "Gourmet Kitchen", city: "Chicago", country: "United States" },
    receiver: { name: "Rachel Monroe", city: "Chicago", country: "United States" },
    origin: "Chicago, USA",
    destination: "Chicago, USA",
    currentLocation: "Chicago, USA",
    estimatedDelivery: daysAgo(0),
    actualDelivery: daysAgo(0),
    shippedDate: daysAgo(0),
    timeline: buildTimeline(STATUS.DELIVERED, "Chicago, USA", "Chicago, USA", 0),
    description: "Restaurant Order",
  },
  {
    id: "NC-2024-021",
    trackingNumber: "NC6078341925",
    status: STATUS.PENDING,
    service: "International Air",
    weight: "4.5 kg",
    dimensions: "42 × 32 × 22 cm",
    sender: { name: "SolarTech GmbH", city: "Munich", country: "Germany" },
    receiver: { name: "GreenEnergy Co.", city: "Cape Town", country: "South Africa" },
    origin: "Munich, Germany",
    destination: "Cape Town, South Africa",
    currentLocation: "Munich, Germany",
    estimatedDelivery: daysFromNow(6),
    shippedDate: daysAgo(0),
    timeline: buildTimeline(STATUS.PENDING, "Munich, Germany", "Cape Town, SA", 0),
    description: "Solar Panels",
  },
  {
    id: "NC-2024-022",
    trackingNumber: "NC3920184765",
    status: STATUS.IN_TRANSIT,
    service: "Express Delivery",
    weight: "1.9 kg",
    dimensions: "28 × 20 × 12 cm",
    sender: { name: "Maple Leaf Exports", city: "Vancouver", country: "Canada" },
    receiver: { name: "Tokyo Imports", city: "Tokyo", country: "Japan" },
    origin: "Vancouver, Canada",
    destination: "Tokyo, Japan",
    currentLocation: "Pacific Air Transit",
    estimatedDelivery: daysFromNow(1),
    shippedDate: daysAgo(3),
    timeline: buildTimeline(STATUS.IN_TRANSIT, "Vancouver, Canada", "Tokyo, Japan", 3),
    description: "Organic Foods",
  },
  {
    id: "NC-2024-023",
    trackingNumber: "NC8451736290",
    status: STATUS.DELIVERED,
    service: "Economy Shipping",
    weight: "6.3 kg",
    dimensions: "55 × 40 × 30 cm",
    sender: { name: "BookNest Publishers", city: "London", country: "United Kingdom" },
    receiver: { name: "Nairobi Library", city: "Nairobi", country: "Kenya" },
    origin: "London, UK",
    destination: "Nairobi, Kenya",
    currentLocation: "Nairobi, Kenya",
    estimatedDelivery: daysAgo(3),
    actualDelivery: daysAgo(3),
    shippedDate: daysAgo(12),
    timeline: buildTimeline(STATUS.DELIVERED, "London, UK", "Nairobi, Kenya", 12),
    description: "Educational Materials",
  },
  {
    id: "NC-2024-024",
    trackingNumber: "NC0297465318",
    status: STATUS.PROCESSING,
    service: "Freight Services",
    weight: "95 kg",
    dimensions: "150 × 100 × 80 cm",
    sender: { name: "Nordic Timber", city: "Oslo", country: "Norway" },
    receiver: { name: "Construction AB", city: "Copenhagen", country: "Denmark" },
    origin: "Oslo, Norway",
    destination: "Copenhagen, Denmark",
    currentLocation: "Oslo Freight Terminal",
    estimatedDelivery: daysFromNow(4),
    shippedDate: daysAgo(1),
    timeline: buildTimeline(STATUS.PROCESSING, "Oslo, Norway", "Copenhagen, Denmark", 1),
    description: "Timber & Building Materials",
  },
  {
    id: "NC-2024-025",
    trackingNumber: "NC7134682905",
    status: STATUS.OUT_FOR_DELIVERY,
    service: "Standard Shipping",
    weight: "3.1 kg",
    dimensions: "35 × 25 × 18 cm",
    sender: { name: "TechGadget US", city: "San Francisco", country: "United States" },
    receiver: { name: "Oliver Hughes", city: "Seattle", country: "United States" },
    origin: "San Francisco, USA",
    destination: "Seattle, USA",
    currentLocation: "Seattle Distribution Center",
    estimatedDelivery: daysFromNow(0),
    shippedDate: daysAgo(3),
    timeline: buildTimeline(STATUS.OUT_FOR_DELIVERY, "San Francisco, USA", "Seattle, USA", 3),
    description: "Consumer Tech",
  },
  {
    id: "NC-2024-026",
    trackingNumber: "NC5309182476",
    status: STATUS.DELIVERED,
    service: "International Air",
    weight: "2.7 kg",
    dimensions: "32 × 24 × 14 cm",
    sender: { name: "Spice World India", city: "Delhi", country: "India" },
    receiver: { name: "Flavour House", city: "New York", country: "United States" },
    origin: "Delhi, India",
    destination: "New York, USA",
    currentLocation: "New York, USA",
    estimatedDelivery: daysAgo(2),
    actualDelivery: daysAgo(2),
    shippedDate: daysAgo(8),
    timeline: buildTimeline(STATUS.DELIVERED, "Delhi, India", "New York, USA", 8),
    description: "Spices & Condiments",
  },
  {
    id: "NC-2024-027",
    trackingNumber: "NC4867293150",
    status: STATUS.IN_TRANSIT,
    service: "Express Delivery",
    weight: "1.6 kg",
    dimensions: "26 × 19 × 11 cm",
    sender: { name: "CryptoGear", city: "Tallinn", country: "Estonia" },
    receiver: { name: "BlockChain Labs", city: "Singapore", country: "Singapore" },
    origin: "Tallinn, Estonia",
    destination: "Singapore",
    currentLocation: "Frankfurt Hub",
    estimatedDelivery: daysFromNow(2),
    shippedDate: daysAgo(2),
    timeline: buildTimeline(STATUS.IN_TRANSIT, "Tallinn, Estonia", "Singapore", 2),
    description: "Hardware Wallets",
  },
  {
    id: "NC-2024-028",
    trackingNumber: "NC1078364592",
    status: STATUS.DELIVERED,
    service: "Same-Day Delivery",
    weight: "4.2 kg",
    dimensions: "45 × 35 × 25 cm",
    sender: { name: "PharmQuick", city: "Paris", country: "France" },
    receiver: { name: "Lena Rousseau", city: "Lyon", country: "France" },
    origin: "Paris, France",
    destination: "Lyon, France",
    currentLocation: "Lyon, France",
    estimatedDelivery: daysAgo(0),
    actualDelivery: daysAgo(0),
    shippedDate: daysAgo(0),
    timeline: buildTimeline(STATUS.DELIVERED, "Paris, France", "Lyon, France", 0),
    description: "Prescription Medication",
  },
  {
    id: "NC-2024-029",
    trackingNumber: "NC6592047381",
    status: STATUS.PENDING,
    service: "Economy Shipping",
    weight: "18.4 kg",
    dimensions: "90 × 65 × 55 cm",
    sender: { name: "EcoGarden Ltd.", city: "Barcelona", country: "Spain" },
    receiver: { name: "Green Spaces NGO", city: "Accra", country: "Ghana" },
    origin: "Barcelona, Spain",
    destination: "Accra, Ghana",
    currentLocation: "Barcelona, Spain",
    estimatedDelivery: daysFromNow(12),
    shippedDate: daysAgo(0),
    timeline: buildTimeline(STATUS.PENDING, "Barcelona, Spain", "Accra, Ghana", 0),
    description: "Garden Tools & Seeds",
  },
  {
    id: "NC-2024-030",
    trackingNumber: "NC3715928064",
    status: STATUS.IN_TRANSIT,
    service: "International Air",
    weight: "5.1 kg",
    dimensions: "48 × 36 × 24 cm",
    sender: { name: "Swiss Precision AG", city: "Geneva", country: "Switzerland" },
    receiver: { name: "Time Boutique", city: "Hong Kong", country: "China" },
    origin: "Geneva, Switzerland",
    destination: "Hong Kong",
    currentLocation: "Dubai International Airport",
    estimatedDelivery: daysFromNow(1),
    shippedDate: daysAgo(4),
    timeline: buildTimeline(STATUS.IN_TRANSIT, "Geneva, Switzerland", "Hong Kong", 4),
    description: "Luxury Watches",
  },
  {
    id: "NC-2024-031",
    trackingNumber: "NC8903746215",
    status: STATUS.DELAYED,
    service: "Freight Services",
    weight: "320 kg",
    dimensions: "250 × 180 × 150 cm",
    sender: { name: "Agri Exports SA", city: "Johannesburg", country: "South Africa" },
    receiver: { name: "EU Food Imports", city: "Rotterdam", country: "Netherlands" },
    origin: "Johannesburg, South Africa",
    destination: "Rotterdam, Netherlands",
    currentLocation: "Port of Cape Town",
    estimatedDelivery: daysFromNow(7),
    shippedDate: daysAgo(10),
    timeline: buildTimeline(STATUS.DELAYED, "Johannesburg, SA", "Rotterdam, NL", 10),
    description: "Agricultural Products",
  },
  {
    id: "NC-2024-032",
    trackingNumber: "NC2164839057",
    status: STATUS.DELIVERED,
    service: "Express Delivery",
    weight: "1.3 kg",
    dimensions: "24 × 18 × 9 cm",
    sender: { name: "Seoul Studios", city: "Seoul", country: "South Korea" },
    receiver: { name: "Pop Culture Shop", city: "Los Angeles", country: "United States" },
    origin: "Seoul, South Korea",
    destination: "Los Angeles, USA",
    currentLocation: "Los Angeles, USA",
    estimatedDelivery: daysAgo(1),
    actualDelivery: daysAgo(1),
    shippedDate: daysAgo(6),
    timeline: buildTimeline(STATUS.DELIVERED, "Seoul, South Korea", "Los Angeles, USA", 6),
    description: "K-Pop Merchandise",
  },
  {
    id: "NC-2024-033",
    trackingNumber: "NC9481703265",
    status: STATUS.PROCESSING,
    service: "Standard Shipping",
    weight: "7.8 kg",
    dimensions: "60 × 45 × 35 cm",
    sender: { name: "Andes Crafts", city: "Lima", country: "Peru" },
    receiver: { name: "World Bazaar", city: "Toronto", country: "Canada" },
    origin: "Lima, Peru",
    destination: "Toronto, Canada",
    currentLocation: "Lima Export Hub",
    estimatedDelivery: daysFromNow(9),
    shippedDate: daysAgo(1),
    timeline: buildTimeline(STATUS.PROCESSING, "Lima, Peru", "Toronto, Canada", 1),
    description: "Handmade Crafts",
  },
  {
    id: "NC-2024-034",
    trackingNumber: "NC5720394861",
    status: STATUS.OUT_FOR_DELIVERY,
    service: "Express Delivery",
    weight: "2.5 kg",
    dimensions: "33 × 24 × 16 cm",
    sender: { name: "Nordic Coffee Co.", city: "Stockholm", country: "Sweden" },
    receiver: { name: "Café Aroma", city: "Copenhagen", country: "Denmark" },
    origin: "Stockholm, Sweden",
    destination: "Copenhagen, Denmark",
    currentLocation: "Copenhagen Central Depot",
    estimatedDelivery: daysFromNow(0),
    shippedDate: daysAgo(2),
    timeline: buildTimeline(STATUS.OUT_FOR_DELIVERY, "Stockholm, Sweden", "Copenhagen, Denmark", 2),
    description: "Premium Coffee Beans",
  },
  {
    id: "NC-2024-035",
    trackingNumber: "NC0638271549",
    status: STATUS.IN_TRANSIT,
    service: "International Air",
    weight: "6.6 kg",
    dimensions: "52 × 40 × 28 cm",
    sender: { name: "NASA Supplier Inc.", city: "Houston", country: "United States" },
    receiver: { name: "ESA Research Lab", city: "Cologne", country: "Germany" },
    origin: "Houston, USA",
    destination: "Cologne, Germany",
    currentLocation: "JFK International Hub",
    estimatedDelivery: daysFromNow(1),
    shippedDate: daysAgo(2),
    timeline: buildTimeline(STATUS.IN_TRANSIT, "Houston, USA", "Cologne, Germany", 2),
    description: "Scientific Equipment",
  },
];

// ─── Utility functions ────────────────────────────────────────────────────────

/** Find a shipment by tracking number (case-insensitive) */
export function findShipment(trackingNumber) {
  return (
    shipments.find(
      (s) => s.trackingNumber.toLowerCase() === trackingNumber.toLowerCase()
    ) || null
  );
}

/** Get summary stats */
export function getStats() {
  const total = shipments.length;
  const delivered = shipments.filter((s) => s.status === STATUS.DELIVERED).length;
  const inTransit = shipments.filter((s) => s.status === STATUS.IN_TRANSIT).length;
  const pending = shipments.filter(
    (s) => s.status === STATUS.PENDING || s.status === STATUS.PROCESSING
  ).length;
  const delayed = shipments.filter((s) => s.status === STATUS.DELAYED).length;
  const outForDelivery = shipments.filter(
    (s) => s.status === STATUS.OUT_FOR_DELIVERY
  ).length;

  return { total, delivered, inTransit, pending, delayed, outForDelivery };
}
